services:

  go-app:
    build: .
    container_name: go-app
    image: scottbrazil/go-app:1.0
    environment:
      DATABASE_URL: "host=db port=5432 user=postgres password=postgres dbname=db-k sslmode=disable"
      #psqlInfo := fmt.Sprintf("host=%s port=%d user=%s password=%s dbname=%s sslmode=disable", host, port, user, password, dbname)
    ports:
      - "7777:7777"
    networks:
      - postgres-docker-k_api_bridge
    command: >
      sh -c "./github.com/scottbrazil/golang-postgres-api-study-docker"

networks:
  postgres-docker-k_api_bridge:
    driver: bridge
    external: true